### ISSUE TITLE
Missing number of cards per list

### ISSUE THREAD

**Issue by yooksi** [christiankaindl/trello-super-powers#33] opened 2021-07-03 11:41 UTC
I can't see the number of cards per list even though I've disabled compact mode and enabled the option in settings.

![Screenshot_2021-07-03_13-40-30](https://user-images.githubusercontent.com/16436920/124353051-4fb25800-dc04-11eb-9c55-108f0b665ee0.png)
![Screenshot_2021-07-03_13-40-50](https://user-images.githubusercontent.com/16436920/124353052-504aee80-dc04-11eb-9c67-8a30b07dea9c.png)

**Comment by christiankaindl** [comment] 2021-10-31 18:32
@yooksi I had a look at this issue today. The CSS selector has NOT changed, so it's something different. I couldn't reproduce the issue myself, but pushed a fixed for a potential cause.

Please update to the lastest version (0.13.1) and let me know if the issue still persists!

**Comment by gregzaal** [comment] 2021-10-31 18:37
Looks like it magically started working again for me a day or two ago :)

**Comment by christiankaindl** [comment] 2021-10-31 19:14
Ok, then let's close this for now. Feel free to open again if it pops up again :)

**Closed by christiankaindl** 2021-10-31 19:14 UTC
